# Generated by Django 4.1.5 on 2023-06-01 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('billno', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('recipient', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('GSTno', models.CharField(max_length=15)),
                ('cgst', models.IntegerField()),
                ('sgst', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grandtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notice', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('itemno', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.TextField(max_length=200)),
                ('hsncode', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billmanage.bill')),
            ],
        ),
    ]
