# Generated by Django 4.1.5 on 2023-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('proforma', 'Pro Forma Invoice'), ('sales', 'Sales Invoice')], default='Quotation', max_length=20),
        ),
    ]
