# Generated by Django 4.1.5 on 2023-06-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0002_bill_bill_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='rate',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hsncode',
        ),
        migrations.AddField(
            model_name='bill',
            name='delivery',
            field=models.TextField(default='no delivery', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_type',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('proforma', 'Proforma Invoice'), ('sales', 'Sales Invoice')], default='Quotation', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='itemcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
