# Generated by Django 4.1.5 on 2023-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0003_rename_rate_item_price_remove_bill_bill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='invoice_type',
            field=models.CharField(choices=[('Quotation', 'quotation'), ('Proforma Invoice', 'proforma'), ('Sales Invoice', 'sales')], default='Quotation', max_length=20),
        ),
    ]
