# Generated by Django 4.1.5 on 2023-06-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0004_alter_bill_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='invoice_type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Proforma Invoice', 'Proforma Invoice'), ('Sales Invoice', 'Sales Invoice')], default='Quotation', max_length=20),
        ),
    ]
