# Generated by Django 4.1.5 on 2023-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0006_alter_bill_invoice_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemcode',
        ),
        migrations.AddField(
            model_name='item',
            name='hsncode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
