# Generated by Django 4.1.5 on 2023-06-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billmanage', '0007_rename_price_item_rate_remove_item_itemcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hsncode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
