# Generated by Django 4.1.5 on 2023-06-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_alter_transaction_quantity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
    ]
