# Generated by Django 4.1.5 on 2023-06-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_alter_customer_table_alter_product_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
