# Generated by Django 4.1.5 on 2023-06-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0004_alter_customer_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='cost_per_case',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount_owed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
