# Generated by Django 4.1.5 on 2023-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0005_alter_transaction_options_transaction_cost_per_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(related_name='customers', to='wholesale.product'),
        ),
    ]
