# Generated by Django 4.1.5 on 2023-06-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0007_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.CreateModel(
            name='TransactionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ManyToManyField(through='wholesale.TransactionProduct', to='wholesale.product'),
        ),
    ]
