# Generated by Django 4.1.5 on 2023-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0009_transactionproduct_cost_per_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionproduct',
            name='cost_per_case',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
