# Generated by Django 4.1.5 on 2023-06-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0010_alter_transactionproduct_cost_per_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionproduct',
            options={'verbose_name_plural': 'Transaction Products'},
        ),
        migrations.AddField(
            model_name='transactionproduct',
            name='total_amount_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
