# Generated by Django 4.1.5 on 2023-06-12 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0011_alter_transactionproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='week_of',
            field=models.DateField(default=datetime.date(2023, 6, 12)),
        ),
    ]
