# Generated by Django 4.1.5 on 2023-06-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_saledetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='buying_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
